### ISSUE TITLE
velveth k range specification [kmin,kmax) is a bit confusing

### ISSUE THREAD

**Issue by sammyjava** [dzerbino/velvet#30]
I ran velveth specifying the k range as 17,31,2, expecting velveth to run k values from 17 to 31 inclusive. But it stopped at 29. In order to get it to include k=31 I have to specify 17,32,2, which seems a bit odd. One doesn't expect that input to specify the interval [kmin,kmax)! Or maybe I'm missing something....

**Comment by dzerbino** [comment]
This is a relic of the seq command in bash or range in python, which are also open-ended. I'm afraid that at this stage changing the syntax would throw off all the people who have their scripts set up already.
