### ISSUE TITLE
MAXKMERLENGTH parameter does not produce any effect on velvelth

### ISSUE THREAD

**Issue by GiBacci** [dzerbino/velvet#31]
Hi,
I'm trying to use velvet + metavelvet to assemble a metagenomic dataset but when I try to construct k-mer hash table with an hash_length of 51 (as suggested in the MetaVelvet pipeline) I get the following error: `Velvet can't handle k-mers as long as 51! We'll stick to 31 if you don't mind.`
I tried to recompile velvet with the `’MAXKMERLENGTH=61` parameter but it didn't work and velveth continues giving me the same error!
Any help would be appreciated!

Thanks in advance

**Comment by dzerbino** [comment]
Hello Giovanni,

I think this can only be answered by the authors of MetaVelvet,
meta@dna.bio.keio.ac.jp

HTH,

Daniel

**Comment by GiBacci** [comment]
Hi Daniel and thanks for the reply,
I think that the problem is in the Velvet `Makefile`. Indeed, when I try to print the help of `velveth` command I get the following message:

```
Compilation settings:
CATEGORIES = 2
MAXKMERLENGTH = 31
```

although I have compiled Velvet with the `MAXKMERLENGTH=61` parameter. I haven't run MetaVelvet yet as I need to construct the k-mer hash table first so I think that this is a Velvet problem. 

Thanks again,

Giovanni

**Comment by dzerbino** [comment]
Could a typo in the command line. What was it exactly?

**Comment by GiBacci** [comment]
I tried to compile it on another machine and it worked! Probably it is some problem related to Ubuntu permissions. However it continues to give some warnings:

```
rm: cannot remove ‘obj/*.o’: No such file or directory
rm: cannot remove ‘obj/dbg/*.o’: No such file or directory
make: [cleanobj] Error 1 (ignored)
src/splayTable.c: In function ‘inputSequenceArrayIntoSplayTableAndArchive’:
src/splayTable.c:1060:14: warning: variable ‘refElem’ set but not used [-Wunused-but-set-variable]
      RefInfo refElem;
              ^
src/splayTable.c: In function ‘scanReferenceSequences’:
src/splayTable.c:877:8: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
   fgets(line, MAXLINE, file);
        ^
src/splayTable.c: In function ‘scanBinaryReferenceSequences’:
src/splayTable.c:933:8: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
   fgets(line, MAXLINE, file);
        ^
src/splayTable.c:949:9: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
    fgets(line, MAXLINE, file);
         ^
src/splayTable.c: In function ‘inputSequenceArrayIntoSplayTableAndArchive’:
src/splayTable.c:1207:11: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
      fgets(line, MAXLINE, seqFile);
           ^
src/splayTable.c:1213:11: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
      fgets(line, MAXLINE, seqFile);
           ^
src/readSet.c: In function ‘readFastXFile’:
src/readSet.c:641:21: warning: assignment from incompatible pointer type [enabled by default]
         file.gzFile = file.autoFile = NULL;
                     ^
src/readSet.c: In function ‘readFastXPair’:
src/readSet.c:680:22: warning: assignment from incompatible pointer type [enabled by default]
         file1.gzFile = file1.autoFile = NULL;
                      ^
src/readSet.c:681:22: warning: assignment from incompatible pointer type [enabled by default]
         file2.gzFile = file2.autoFile = NULL;
                      ^
src/binarySequences.c: In function ‘importCnyReadSet’:
src/binarySequences.c:314:12: warning: variable ‘refElem’ set but not used [-Wunused-but-set-variable]
    RefInfo refElem;
            ^
src/autoOpen.c: In function ‘pcloseNoStderr’:
src/autoOpen.c:49:6: warning: variable ‘rc’ set but not used [-Wunused-but-set-variable]
  int rc, status;
      ^
src/autoOpen.c: In function ‘popenNoStderr’:
src/autoOpen.c:28:6: warning: ignoring return value of ‘dup’, declared with attribute warn_unused_result [-Wunused-result]
   dup(out[1]);
      ^
```

I think they are not really important but still they are there  :)

Thanks again!

Giovanni

**Comment by flydoc2000** [comment]
I'm having the same problem, using Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-59-generic x86_64). I've tried recompiling, also tried editing the Makefile so line 6 is MAXKMERLENGTH?=111, but no luck, it still insists on 31. Thanks for any help you can provide!
Alan

**Comment by flydoc2000** [comment]
Never mind! It seems to have been a problem with the zlib that I already had installed. Using 'BUNDLEDZLIB=1' made it behave and it works now.

**Comment by dzerbino** [comment]
A-ha thanks for figuring it out. I'll leave this issue open for other users to find.

**Comment by shrutidabral** [comment]
I'm having same problem, I tried to do these command

make clean 
make MAXKMERLENGTH=49 
make velveth velvetg 
 I try to run command still it gives
[0.000000] Velvet can't handle k-mers as long as 33! We'll stick to 31 if you don't mind.

when I try to print  velveth command I get the following message:

velveth - simple hashing program
Version 1.2.09

Copyright 2007, 2008 Daniel Zerbino (zerbino@ebi.ac.uk)
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compilation settings:
CATEGORIES = 2
MAXKMERLENGTH = 31


I also check installation for zlib . this is up to date .
Any help would be appreciated!
thankyou
