### ISSUE TITLE
Running into a segmentation fault

### ISSUE THREAD

**Issue by sagnikbanerjee15** [dzerbino/velvet#32]
Hello,

I have generated some assemblies using different settings of the hash length. After that I am trying to merge the assemblies into one. For this step the velveth command runs smoothly but the velvetg command runs into a segmentation fault. I have tried a few different values of K but for all the values I encountered the same error.
Please help.

The command I execute are:

<pre>
velveth ../../data/trimmed/S9/velvet_assemblies/velvet_merged 41 -long ../../data/trimmed/S9/velvet_assemblies/velvet_*/transcripts.fa

velvetg ../../data/trimmed/S9/velvet_assemblies/velvet_merged -read_trkg yes -conserveLong yes
</pre>

**Comment by dzerbino** [comment]
Hello @sagnikbanerjee15, apologies for the delayed response. I'm afraid I would need more info to determine the origin of the fault. Could you please fill a bug report as described at the end of the manual?
