### ISSUE TITLE
Right sequence file has too many reads

### ISSUE THREAD

**Issue by madmolecularman** [dzerbino/velvet#36]
Hello! 

Hope your having a nice day. I am currently having some issues with velveth during transcriptome assembly of illumina paired end reads. I have concatenated the reads into left and right normalized reads that have different coverages of 30 and 100. I am running velveth on these normalized reads. The normalization program came from trinity's program. I seem to be having an issue with creating the de brujin graph and getting the roadmap.

Error:

"velveth: Right sequence file '/projects/rockfish/transcriptomics/EXP7_Scarn_larvae/PE/Assembly/brown_rockfish_larv_EXP7_norm_30/right.norm.fq' has too many sequences
velveth: Right sequence file '/projects/rockfish/transcriptomics/EXP7_Scarn_larvae/PE/Assembly/brown_rockfish_larv_EXP7_norm_30/right.norm.fq' has too many sequences
velveth: Right sequence file '/projects/rockfish/transcriptomics/EXP7_Scarn_larvae/PE/Assembly/brown_rockfish_larv_EXP7_norm_30/right.norm.fq' has too many sequences
velveth: Right sequence file '/projects/rockfish/transcriptomics/EXP7_Scarn_larvae/PE/Assembly/brown_rockfish_larv_EXP7_norm_30/right.norm.fq' has too many sequences
velveth: Right sequence file '/projects/rockfish/transcriptomics/EXP7_Scarn_larvae/PE/Assembly/brown_rockfish_larv_EXP7_norm_30/right.norm.fq' has too many sequences
velveth: Right sequence file '/projects/rockfish/transcriptomics/EXP7_Scarn_larvae/PE/Assembly/brown_rockfish_larv_EXP7_norm_30/right.norm.fq' has too many sequences" 

The right.norm.fq file has 66909286
The left.norm.fq file has 66009874
The sequences file from oases_velh100_19 has 132019748

This makes sense as it is a concatenation of these two files but it seems to not be resolving it into a roadmap. Should I do an extra step in normalizing or qc for these reads. Thanks for your time!

Sincerely, 

The Madmolecularman

**Comment by madmolecularman** [comment]
Forgot to add the input for the run. 

for i in 19 25 31 37 43 49
do
  /opt/velvet_1.2.10/velveth /projects/rockfish/transcriptomics/EXP7_Scarn_larvae/PE/Assembly/oases_velh100_$i $i -fastq -shortPaired -separate /projects/rockfish/transcriptomics/EXP7_Scarn_larvae/PE/Assembly/brown_rockfish_larv_EXP7_norm_100/left.norm.fq /projects/rockfish/transcriptomics/EXP7_Scarn_larvae/PE/Assembly/brown_rockfish_larv_EXP7_norm_100/right.norm.fq > /projects/rockfish/transcriptomics/EXP7_Scarn_larvae/PE/Assembly/brown_rockfish_larv_EXP7_oases_velh_$i_out_100.txt
done; 

Thanks for your time!

**Comment by madmolecularman** [comment]
Found out my issue! The normalized reads need to have the same number of sequences. Don't know why the first normalization was weird, but the second iteration and a few extra commands solved it.

**Comment by dzerbino** [comment]
Hello @madmolecularman , Sorry for the slow response, glad you sorted it out in the end.
