### ISSUE TITLE
Velvetg failed at k =25

### ISSUE THREAD

**Issue by MochiGirl** [dzerbino/velvet#37]
@dzerbino Hey! This is my first time posting on github and I and my contacts at IT have not been able to figure this error out. Please help if you can! as my background is in biology and not the computational kind :) 

I have ~76 GB of sequencing data (100 bp PE and 150 bp PE runs on Illumina HiSeq 2000) stored in 620 million reads. My kmers are 35 - 145, stepping by 10, and I've been submitting the oases_pipeline.py over a shared computing cluster with 1024 GB of memory on the node and a time limit of 72 hours. (I've since increased it to 240 hours... run is waiting in the queue.) 

I attached the error message here.
[AstrangiaT1VOo149179.txt](https://github.com/dzerbino/velvet/files/1203161/AstrangiaT1VOo149179.txt)

IT has said, "usually we don't see errors when a job is killed for exceeding time -- so it's possible that there is an issue in the program that causes it to hang. The output directories and corresponding sizes are below. You can see that the k=25 step used much more space than any of the others. k=25 is your lowest step which seems to indicated it didn't get very far.

$ ls -1 /transcriptomes | grep Astrangia_Assembly_T1_ | grep -v low | xargs -i du -hs /projectnb/cnidaria/nguyenl/transcriptomes/{}
12G	/transcriptomes/Astrangia_Assembly_T1_105
12G	/transcriptomes/Astrangia_Assembly_T1_115
11G	/transcriptomes/Astrangia_Assembly_T1_125
11G	/transcriptomes/Astrangia_Assembly_T1_135
9.5G	/transcriptomes/Astrangia_Assembly_T1_145
450G	/transcriptomes/Astrangia_Assembly_T1_25
38G	/transcriptomes/Astrangia_Assembly_T1_35
35G	/transcriptomes/Astrangia_Assembly_T1_45
32G	/transcriptomes/Astrangia_Assembly_T1_55
31G	/transcriptomes/Astrangia_Assembly_T1_65
29G	/transcriptomes/Astrangia_Assembly_T1_75
28G	/transcriptomes/Astrangia_Assembly_T1_85
25G	/transcriptomes/Astrangia_Assembly_T1_95
32K	/transcriptomes/Astrangia_Assembly_T1_Merged"

Please advise!

**Comment by dzerbino** [comment]
Hello @MochiGirl, 

Apologies for the slow response. I think your IT team's comment is on target. As 25 is a very small k-mer length, you end up with a very tangled graph with tiny nodes. It's hard to guess why exactly k=25 failed (too much memory? file size? timeout?) but it is fair to say that if this graph is so much bigger  than the others, then it is possibly noisier than the rest, so I would avoid that value of k altogether. 

Sorry for not providing deeper insight on the cause of the crash, but the output was visibly truncated, so it's anyone's guess what happened.

Hope this helps,

Daniel
