### ISSUE TITLE
velvetg: Cannot allocate memory

### ISSUE THREAD

**Issue by rominahenriques** [dzerbino/velvet#38]
Hello,

I'm trying to run VelvetOptimizer on four samples with 3 million reads on average (x2 as they are paired-reads). Although velveth works and produces the expected outputs, velvetg seems to be crashing, even when I run it manually (please see below)

This is the input script:
VelvetOptimiser.pl -s 33 -e 121 -t 8 -f '-shortPaired -separate -fastq CNN_R1_val_1.fq CNN_R2_val_2.fq'
and it generates auto_data files from 33 to 12. However, when vanilla velvetg is supposed to run, it crashes.

Example of the error file:
Oct 6 17:11:08	Running vanilla velvetg on hash value: 49
velvetg: Can't calloc 281474976710656 void*s totalling 2251799813685248 bytes: Cannot allocate memory
This happens for the majority of hash values, and the end of the error file says:
Oct 6 17:12:26 Hash value of best assembly by assembly score: 97
Oct 6 17:12:26 Optimisation routine chosen for best assembly: shortPaired
Oct 6 17:12:26 Looking for the expected coverage
Unable to open /home/rhenriques/capensis/Rainbow_Tr50/trimmed/50e001/auto_data_97/stats.txt for exp_cov determination.
at /apps/velvet/1.2.10-9adf09f-KMER121/contrib/VelvetOptimiser-2.2.5/VelvetOptimiser.pl line 859.

When I try to run velvetg manually using the script
velvetg /home/rhenriques/capensis/Rainbow_Tr50/trimmed/50e001/auto_data_97

I get this error message:
velvetg: Can't calloc 281474976710656 void*s totalling 2251799813685248 bytes: Cannot allocate memory

Can you please let me know how to proceed?
Thank you!

Cheers,
Romina

**Comment by dzerbino** [comment]
Hello Romina,

Apologies for the delayed response.

I'm afraid this is simply because there is too much data for Velvetg to handle (within your machine's memory). It could be due to the k-mer length which is very long indeed. Did the run work on shorter k-mer lengths? 

Cheers,

Daniel

**Comment by yeroslaviz** [comment]
This is not correct, as version 1.1.07 can run with similar parameters without giving this error.

**Comment by franztastic** [comment]
Dearest, 
I am having the same error. 
Where could I find the 1.1.07 version?

Thank you very much,
