### ISSUE TITLE
kmerge option for oases_pipeline.py

### ISSUE THREAD

**Issue by minor7b5** [dzerbino/velvet#39]
Hi,

Running the script with this option tells me that this needs to be an integer. Please forgive my ignorance but I cannot find anywhere in the documentation or online that explains what integer this is supposed to be or what range - and what effect this has on the multi-k assembly.

Can you please provide some insight?

Thank you very much.

**Comment by dzerbino** [comment]
Hello @minor7b5 ,

Apologies for the delay in responding. The k-mer parameter is discussed in length in our publication:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3324515/

Cheers,

Daniel
