### ISSUE TITLE
rerunning velvetg

### ISSUE THREAD

**Issue by Koorvo** [dzerbino/velvet#40]
Hello and sorry if that question looks stupid, I'm newbie not only with velvet.

I have searched for that in biostar and other forums.

My problem is about rerun velvet jobs, specially velvetg. For example I ran this command which demands a lot of RAM:

velvetg dir_27 -read_trkg yes -ins_length 240 1>dir_27.log 2>dir_27.err

To run that I need 700GB of RAM so I have to use HPC resources froma  server, and obviusly I have to reserve time.

My question is, can I recover a job of velvetg which stop cause to timeout? because when I rerun the command it just overwrite the previous output.

Thank you

**Comment by dzerbino** [comment]
Hello @Koorvo ,

Sincere apologies for the delay in answering. No, Velvet has no timepointing functionalities so interrupted jobs needs to be started again.

Cheers,

Daniel
