### ISSUE TITLE
how to extract Unmatched reads paired and Unmatched reads unpaired

### ISSUE THREAD

**Issue by shrutidabral** [dzerbino/velvet#41]
hello ,
I am doing a project on metagenomics.
I complete the assembly process by using velvet software.
Now, i have  to find Unmatched reads paired and Unmatched reads unpaired reads in data. 

Can you please help me out .

thankyou in advance

**Comment by dzerbino** [comment]
Hello @shrutidabral ,

What do you mean by unmatched? If you mean reads that did not map into contigs, you can use the '-unused_reads' flag.

HTH,

Daniel

**Comment by shrutidabral** [comment]
hello Daniel 

Thankyou for your reply .

Unmatched reads means unmapped reads .

For that i did this ---

1. make the indexing file for contigs . [using bowtie command]
2. Alignment of raw file with index [using bowtie ]
command is --- bowtie2 -p 4 --local -x B1 -1 R1.fastq.gz -2 R2.fastq.gz --un unpaired.fq --un-conc paired_unmapped.fq -S R12.sam

after executing this i get unpaired mapped reads and paired mapped reads .

Is this correct way to do this .

**Comment by dzerbino** [comment]
This is also seems correct.
