### ISSUE TITLE
error in increasing Kmer lenght from 31 to 51

### ISSUE THREAD

**Issue by shrutidabral** [dzerbino/velvet#42]
I want  to run velevth on 51 kmer but i am getting error.

 I tried to do these commandmake 
cleanmake 
MAXKMERLENGTH=51
make velveth
 velvetg

I try to run command still it gives
[0.000000] Velvet can't handle k-mers as long as 33! We'll stick to 31 if you don't mind.

when I try to print velveth command I get the following message:

velveth - simple hashing 
programVersion 1.2.09

Copyright 2007, 2008 Daniel Zerbino (zerbino@ebi.ac.uk)This is free software; see the source for copying conditions. There is NOwarranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compilation settings:CATEGORIES = 2MAXKMERLENGTH = 31

I also check installation for zlib . this is up to date .
Any help would be appreciated!
thankyou
--

**Comment by jmarshall** [comment]
For velvet, **just run make only once**:

    make MAXKMERLENGTH=51

Velvet has a somewhat unusual makefile whose default target does a full clean and rebuild, which is convenient for the one-shot builds that most users are doing.

Incidentally, you appear not to be using the final version of velvet (1.2.10) or the code in this git repository, which contains a couple of additional small fixes.

**Comment by shrutidabral** [comment]
Thankyou for your kind consideration.  :+1:
