### ISSUE TITLE
Where can I download Velvet 1.2.08_maxkmer101

### ISSUE THREAD

**Issue by ShuChen1986** [dzerbino/velvet#44]
Dear Sir/Madam,

I wan to use kmer larger than 32. I used to have a version Velvet 1.2.08_maxkmer101, but I could not find it now. Could you please inform me where I can download this version? Thank you so much!

Shu

**Comment by dzerbino** [comment]
Dear Shu,

I'm afraid we do not distribute compiled packages of Velvet, rather source packages for you to compile. 

Best regards,

Daniel
