### ISSUE TITLE
Segmentation fault for velveth on short paired separate reads

### ISSUE THREAD

**Issue by spencel** [dzerbino/velvet#46]
Ran the command below on Bridges. Made sure I had the velvet module loaded. Its version is 1.2.10-maxk63-categ14-big.

`$ velveth velvet 63 -shortPaired -fastq.gz -separate SRR8547393_1.fastq.gz SRR8547393_2.fastq.gz`

The error below is returned follow by the command.

`velvet.sh: line 5: 25824 Segmentation fault`

Tried finding a solution and playing with file formats and kmer length but nothing worked. There's no mention of segmentation fault in the manual.

Update:
I tried cloning velvet from the git repo and making it. Ran into the same error above.

**Comment by dzerbino** [comment]
Hello @spencel,

Could you please provide some context on the environment. In particular, what is Bridges, what velvet module are you referring to, and what is that velvet.sh script?

Thank you,

Daniel

**Comment by dzerbino** [comment]
This thread has gone silent for a year, now closing.
