### ISSUE TITLE
cannot run velvet (1.2.10)

### ISSUE THREAD

**Issue by memaMJ** [dzerbino/velvet#47]
Hello, 
**velveth out_data_35 35 -fastq.gz -shortPaired -separate SRR292770_1.fastq.gz SRR292770_2.fastq.gz**
I run the following command but it did not work..... and I got this message
""-bash: $: command not found""

I fix it to be  **> ./velveth out_data_35 35 -fastq.gz -shortPaired -separate SRR292770_1.fastq.gz SRR292770_2.fastq.gz**
then I got " -bash: out_data_35: command not found " 

am not sure how to fix this and run the Velveth software..

kindly help me out ... what should I do ?

**Comment by dzerbino** [comment]
Hello @memaMJ ,

Apologies, I had totally missed this ticket. 

This appears to be an issue with your bash settings, I'm afraid I cannot diagnose it.

Best regards,

Daniel
