### ISSUE TITLE
How to choose kmer length?

### ISSUE THREAD

**Issue by XMTian** [dzerbino/velvet#48]
Hello,

I'm using velvet to assemble genomes,  but I don't know how to choose kmer length.
I tried to use velvetoptimiser, but I failed in the installation. 
So can you tell me how to choose by myself?

Thanks a lot.

**Comment by dzerbino** [comment]
Dear @XMTian ,

Please refer to our short summary here: https://www.ebi.ac.uk/~zerbino/velvet/hash_length_choice.html

Or a longer explanation here: https://currentprotocols.onlinelibrary.wiley.com/doi/abs/10.1002/0471250953.bi1105s31

Best regards,

Daniel
