### ISSUE TITLE
short read and reference as input to velvet

### ISSUE THREAD

**Issue by azrasid** [dzerbino/velvet#49]
Hi , 
I am trying to get some big contigs from the velvet by  using reference as long read.

I tried this command

velveth out_data_78 31 -fastq -shortPaired -separate NA12878_R1.fq NA12878_R2.fq -long -fasta cyp2c19ref.fa

velvetg out_data_78 -exp_cov auto -cov_cutoff auto

Is it the right way to do it? 
Didn't get any error but I am getting huge amount of Ns.

Please help me with the command to achieve it.

Azra

**Comment by dzerbino** [comment]
Hello @azrasid ,

You might be interested in the [Columbus module](https://github.com/dzerbino/velvet/blob/master/Columbus_manual.pdf).

Hope this helps,

Daniel
