### ISSUE TITLE
Reference as input to velvet is giving smaller contig length than without reference.

### ISSUE THREAD

**Issue by azrasid** [dzerbino/velvet#50]
HI ,
I am trying to get a big node length (contig) from the velvet assembly.
For that I used reference and Fastq as input to it.

**velveth out 31 -reference  cyp2c19ref.fa  -fastq -shortPaired -separate cyp2c19/NA12878_R1.fq  NA12878_R2.fq**

and then I used Velvetg

**velvetg out_data_78 -exp_cov auto -cov_cutoff auto.**

I was expecting some big node length contig but I got small length node contigs( smaller than that I was getting when I didn't use the reference). 
I wonder why the length of contigs are larger with pure denovo assembly than with reference when given as input.

Am I doing right steps?
Please help me with this.

Regards,
Azra

**Comment by dzerbino** [comment]
Hello @azrasid ,

The directories used with velveth and velvetg do not match. Is that normal?

Cheers,

Daniel

**Comment by azrasid** [comment]
Sorry.  I pasted the wrong command.
Actually they are matching
velvetg out -exp_cov auto -cov_cutoff auto.

**Comment by dzerbino** [comment]
Hello Azra,

It's hard to diagnose remotely, but this looks correct, as far as I can see. 

Have you tried mapping your sequences to the reference, and providing them as a BAM file? The alignments can then be used by Velvet. 

It's been a while, so I don't remember what happens to unmapped read in FastQ files. 

Cheers,

Daniel

**Comment by azrasid** [comment]
You suggesting me to map Fastq sequences to the reference and get a Bam file. And then use this BAM file as an input to the Velvet?
Really appreciate your response.

**Comment by dzerbino** [comment]
Yes, exactly.

**Comment by azrasid** [comment]
Thanks.
