### ISSUE TITLE
Contig length

### ISSUE THREAD

**Issue by azrasid** [dzerbino/velvet#51]
Hi, 
I am using velvet to de novo assemble a gene.
I got contigs and scaffolds.
Is there any way to improve the quality of contigs- a good length of contig.

Your suggestions will be highly appreciated.

Thanks,
Azra

**Comment by dzerbino** [comment]
Hello Azra,

There are a number of ways. In short it really depends on the data available: do you have paired end reads, long reads etc? 

The setting of parameters, in particular the hash length and coverage cutoff can also be adjusted to improve results. More information here: https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/0471250953.bi1105s31?casa_token=oFVJez9KtigAAAAA%3Af6Fi2dJ6rBASq8xikrW7wUjhYj85BEUlLOsVqon3CgZ_ifMcoXU63pCsn-A9XQW74-3WRhXrhh3cKkvV

Hope this helps,

Daniel

**Comment by azrasid** [comment]
Yes it is helpful.
Thanks and best wishes.
