### ISSUE TITLE
scaffold N50 versus contig N50

### ISSUE THREAD

**Issue by rainbow218** [dzerbino/velvet#52]
Hello,

I have a query and hope to get some feedback. I am using Velvet to assemble draft bacterial genomes and after assembly there are two separate criteria that is required to assess the assembly:
1. scaffold N50 > 20Kb
2. contig N50 > 5Kb

From the Velvet manual, I am under the impression that contigs.fa output file contains both scaffolds and contigs. How do I obtain the N50 value for scaffold and contigs separately in an efficient manner?

thank you for your kind attention!

**Comment by dzerbino** [comment]
Dear @rainbow218 ,

Alas Velvet does not distinguish contigs from scaffolds, rather the Velvet scaffolds are just contigs broken up by rows of N's. The calculated N50 is thus the scaffold N50.

If you do not provide the `-exp_cov`  parameter (as a number or `auto`), then Velvet does not performing scaffolding, in which case you will be obtaining actual contigs.

Another approach is to run Velvet as normal, then break up your contigs each time you see a run of N's to obtain the contigs and compute the N50 off those. 

Hope this helps,

Daniel

**Comment by rainbow218** [comment]
Hi @dzerbino ,

thank you for your feedback,  I have a follow up question:
I did indicate the -exp_cov parameter while assembling the genomes, however I did not observe any run of N's in any of the scaffolds. If there is no run of N's does it mean that it is not a scaffold? (Can there be a scaffold that does not contain run of N's ?)

**Comment by dzerbino** [comment]
Hello @rainbow218 ,

This is all pretty semantic, but if a Velvet contig does not contain any N's then you can treat it like a scaffold with a single contig. 

Hope this helps,

Daniel
