### ISSUE TITLE
MAXKMERLENGTH = 255

### ISSUE THREAD

**Issue by joseboas** [dzerbino/velvet#55]
I want to change the MAXKMERLENGTH to 255. I downloaded the conda version.

**Comment by dzerbino** [comment]
Hello Jose, 

The change the MAXKMERLENGTH you need to download and recompile the source code as explained in the Manual.

I don't know if that is possible with conda and may require you downloading the Git repository itself: https://github.com/dzerbino/velvet/archive/refs/heads/master.zip

Best regards,

Daniel

**Comment by joseboas** [comment]
OK. Thanks for the feedback.

**Comment by bernt-matthias** [comment]
The velvet version provided by bioconda currently sets the value to 191: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/velvet/build.sh

If you like to use 255 you may open a PR to the bioconda recipes repo.
